server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ticket-service
          uri: lb://ticket-service
          predicates:
            - Path=/ticket/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account/**
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8500/eureka
