version: "2"

services:
  cassandra:
    image: cassandra
    ports:
      - "9042:9042"

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: microserviceapp

  elasticsearch:
    image: elasticsearch:6.4.1
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"