server:
  port: 8501

spring:
  application:
    name: account-service

spcloud:
  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: springcloud
    username: cassandra
    password: cassandra