server:
  port: 8501

spring:
  application:
    name: account-service
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  boot:
    admin:
      client:
        url: http://localhost:9090

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka

spcloud:
  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: springcloud
    username: cassandra
    password: cassandra

springdoc:
  api-docs:
    path: "/api-docs"
    enabled: true
  swagger-ui:
    path: "/docs"