server:
  port: 8500

spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  boot:
    admin:
      client:
        url: http://localhost:9090

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
