server:
  port: 8503

spring:
  application:
    name: notification-service
  cloud:
    stream:
      function:
        definition: processNotification
      bindings:
        processNotification-in-0:
          destination: msqueue
  rabbitmq:
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  boot:
    admin:
      client:
        url: http://localhost:9090

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka

springdoc:
  api-docs:
    path: "/api-docs"
    enabled: true
  swagger-ui:
    path: "/docs"