server:
  port: 8503

spring:
  application:
    name: notification-service
  cloud:
    stream:
      function:
        definition: processNotification
      bindings:
        processNotification-in-0:
          destination: msqueue
  rabbitmq:
    username: guest
    password: guest
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka

springdoc:
  api-docs:
    path: "/api-docs"
    enabled: true
  swagger-ui:
    path: "/docs"