server:
  port: 8502

spring:
  application:
    name: ticket-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_app
    username: root
    password: microserviceapp
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    stream:
      function:
        definition: sendMessage
      bindings:
        sendMessage-out-0:
          destination: msqueue
  rabbitmq:
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  boot:
    admin:
      client:
        url: http://localhost:9090

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: "/api-docs"
    enabled: true
  swagger-ui:
    path: "/docs"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka